import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#C08B8B',
  DRUMS_SECONDARY: '#D09B9B',
  BASS_MAIN: '#B07A7A',
  HIHAT_MAIN: '#C08B8B',
  MELODY_MAIN: '#C0A08B',
  MELODY_SECONDARY: '#C0A08B',
  SYNTH_MAIN: '#C0A08B',
};

const soundPack: SoundPack = {
  id: 'area51',
  name: 'Area 51',
  genre: 'Trap',
  bpm: '140',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'dark',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare: require('./samples/snare.mp3'),
    clap: require('./samples/clap.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    hi_hat_roll: require('./samples/hi_hat_roll.mp3'),
    '808': require('./samples/808.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_1_3: require('./samples/melody_1_3.mp3'),
    melody_1_4: require('./samples/melody_1_4.mp3'),
    melody_1_5: require('./samples/melody_1_5.mp3'),
    synth: require('./samples/synth.mp3'),
  },
  soundGroups: {
    melody_1: ['melody_1_1', 'melody_1_2', 'melody_1_3', 'melody_1_4', 'melody_1_5'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 3,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 4,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 5,
      sound: 'hi_hat_roll',
      color: PAD_COLORS.HIHAT_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat Roll',
    },
    {
      id: 6,
      sound: '808',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'bass',
      title: '808',
    },
    {
      id: 7,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 8,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 9,
      sound: 'melody_1_3',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 10,
      sound: 'melody_1_4',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 11,
      sound: 'melody_1_5',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody V',
    },
    {
      id: 12,
      sound: 'synth',
      color: PAD_COLORS.SYNTH_MAIN,
      icon: 'synth',
      title: 'Synth',
    },
  ],
};

export default soundPack;
