import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#1A0A1A',
  DRUMS_SECONDARY: '#2A1A2A',
  MELODY_MAIN: '#2A1A3A',
  MELODY_SECONDARY: '#3A2A4A',
  SYNTH_MAIN: '#2A1A3A',
};

const soundPack: SoundPack = {
  id: 'flex',
  name: 'Flex',
  genre: 'Trap',
  bpm: '140',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'dark',
  sounds: {
    drums_1_1: require('./samples/drums_1_1.mp3'),
    drums_1_2: require('./samples/drums_1_2.mp3'),
    drums_1_3: require('./samples/drums_1_3.mp3'),
    drums_1_4: require('./samples/drums_1_4.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_1_3: require('./samples/melody_1_3.mp3'),
    melody_2_1: require('./samples/melody_2_1.mp3'),
    melody_2_2: require('./samples/melody_2_2.mp3'),
    melody_2_3: require('./samples/melody_2_3.mp3'),
    synth: require('./samples/synth.mp3'),
  },
  soundGroups: {
    drums_1: ['drums_1_1', 'drums_1_2', 'drums_1_3', 'drums_1_4'],
    melody_1: ['melody_1_1', 'melody_1_2', 'melody_1_3'],
    melody_2: ['melody_2_1', 'melody_2_2', 'melody_2_3'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'drums_1_1',
      color: PAD_COLORS.DRUMS_MAIN,
      group: 'drums_1',
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 2,
      sound: 'drums_1_2',
      color: PAD_COLORS.DRUMS_MAIN,
      group: 'drums_1',
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 3,
      sound: 'drums_1_3',
      color: PAD_COLORS.DRUMS_MAIN,
      group: 'drums_1',
      icon: 'drums',
      title: 'Drums III',
    },
    {
      id: 4,
      sound: 'drums_1_4',
      color: PAD_COLORS.DRUMS_SECONDARY,
      group: 'drums_1',
      icon: 'drums',
      title: 'Drums IV',
    },
    {
      id: 5,
      sound: 'drums_2',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'drums',
      title: 'Drums V',
    },
    {
      id: 6,
      sound: 'synth',
      color: PAD_COLORS.SYNTH_MAIN,
      icon: 'synth',
      title: 'Synth',
    },
    {
      id: 7,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 8,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 9,
      sound: 'melody_1_3',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 10,
      sound: 'melody_2_1',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 11,
      sound: 'melody_2_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody V',
    },
    {
      id: 12,
      sound: 'melody_2_3',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody VI',
    },
  ],
};

export default soundPack;
