import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#E0F8FF',
  DRUMS_SECONDARY: '#F0FFFF',
  PERC_MAIN: '#E6F3FF',
  PERC_SECONDARY: '#F2F8FF',
  MELODY_MAIN: '#FFE6F7',
  MELODY_SECONDARY: '#FFF0FB',
  SYNTH_MAIN: '#E6E6FF',
  SYNTH_SECONDARY: '#F0F0FF',
  SFX_MAIN: '#FFEBE6',
  SFX_SECONDARY: '#FFF2ED',
};

const soundPack: SoundPack = {
  id: 'energy',
  name: 'Energy',
  genre: 'Hip Hop',
  bpm: 140,
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    clap: require('./samples/clap.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    hi_hat_roll: require('./samples/hi_hat_roll.mp3'),
    hit: require('./samples/hit.mp3'),
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    synth_1: require('./samples/synth_1.mp3'),
    synth_2: require('./samples/synth_2.mp3'),
    sfx_walkie_talkie: require('./samples/sfx_walkie_talkie.mp3'),
    chant_female: require('./samples/chant_female.mp3'),
  },
  soundGroups: {
    melody: ['melody_1', 'melody_2'],
    synth: ['synth_1', 'synth_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 3,
      sound: 'hi_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 4,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 5,
      sound: 'hit',
      color: PAD_COLORS.PERC_SECONDARY,
      icon: 'hit',
      title: 'Hit',
    },
    {
      id: 6,
      sound: 'hi_hat_roll',
      color: PAD_COLORS.PERC_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat Roll',
    },
    {
      id: 7,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 8,
      sound: 'synth_1',
      color: PAD_COLORS.SYNTH_MAIN,
      group: 'synth',
      icon: 'synth',
      title: 'Synth I',
    },
    {
      id: 9,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 10,
      sound: 'synth_2',
      color: PAD_COLORS.SYNTH_SECONDARY,
      group: 'synth',
      icon: 'synth',
      title: 'Synth II',
    },
    {
      id: 11,
      sound: 'chant_female',
      color: PAD_COLORS.SFX_SECONDARY,
      icon: 'chant',
      title: 'Female Chant',
    },
    {
      id: 12,
      sound: 'sfx_walkie_talkie',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'walkieTalkie',
      title: 'Walkie Talkie',
    },
  ],
};

export default soundPack;
