import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#FFB3B3',
  DRUMS_SECONDARY: '#FFC9C9',
  MELODY_MAIN: '#FFFFB3',
  MELODY_SECONDARY: '#FFFFC9',
  SFX_MAIN: '#D3D3D3',
  SFX_SECONDARY: '#E6E6E6',
  PERC_MAIN: '#D3D3D3',
  PERC_SECONDARY: '#E6E6E6',
  BELLS_MAIN: '#B3B3FF',
  BELLS_SECONDARY: '#C9C9FF',
  CHANT_MAIN: '#FFB3CC',
  CHANT_SECONDARY: '#FFC9DD',
};

const soundPack: SoundPack = {
  id: 'xmas',
  name: 'Xmas',
  genre: 'Trap',
  bpm: 120,
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'dark',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare: require('./samples/snare.mp3'),
    clap: require('./samples/clap.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    bells_1: require('./samples/bells_1.mp3'),
    bells_2: require('./samples/bells_2.mp3'),
    chant_merry_christmas: require('./samples/chant_merry_christmas.mp3'),
    chant_christmas_morning: require('./samples/chant_christmas_morning.mp3'),
  },
  soundGroups: {
    melody: ['melody_1', 'melody_2', 'melody_3'],
    bells: ['bells_1', 'bells_2'],
    chant: ['chant_merry_christmas', 'chant_christmas_morning'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 3,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 4,
      sound: 'hi_hat',
      color: PAD_COLORS.PERC_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 5,
      sound: 'open_hat',
      color: PAD_COLORS.PERC_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 6,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 7,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 8,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 9,
      sound: 'bells_1',
      color: PAD_COLORS.BELLS_MAIN,
      group: 'bells',
      icon: 'bells',
      title: 'Bells I',
    },
    {
      id: 10,
      sound: 'bells_2',
      color: PAD_COLORS.BELLS_SECONDARY,
      group: 'bells',
      icon: 'bells',
      title: 'Bells II',
    },
    {
      id: 11,
      sound: 'chant_merry_christmas',
      color: PAD_COLORS.CHANT_MAIN,
      group: 'chant',
      icon: 'chant',
      title: 'Merry Christmas',
    },
    {
      id: 12,
      sound: 'chant_christmas_morning',
      color: PAD_COLORS.CHANT_SECONDARY,
      group: 'chant',
      icon: 'chant',
      title: 'Christmas Morning',
    },
  ],
};

export default soundPack;
