import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#F5F5F0',
  DRUMS_SECONDARY: '#E8E8E0',
  MELODY_MAIN: '#FFF8E1',
  MELODY_SECONDARY: '#FFF3C4',
  SYNTH_MAIN: '#F0F8FF',
  SYNTH_SECONDARY: '#E0F0FF',
};

const soundPack: SoundPack = {
  id: 'destiny',
  name: 'Destiny',
  genre: 'Lo-Fi',
  bpm: '90',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare: require('./samples/snare.mp3'),
    clap: require('./samples/clap.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_1_3: require('./samples/melody_1_3.mp3'),
    melody_1_4: require('./samples/melody_1_4.mp3'),
    melody_1_5: require('./samples/melody_1_5.mp3'),
    melody_1_6: require('./samples/melody_1_6.mp3'),
    synth_1: require('./samples/synth_1.mp3'),
    synth_2: require('./samples/synth_2.mp3'),
  },
  soundGroups: {
    melody_1: ['melody_1_1', 'melody_1_2', 'melody_1_3', 'melody_1_4', 'melody_1_5', 'melody_1_6'],
    synth: ['synth_1', 'synth_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 3,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 4,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 5,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 6,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 7,
      sound: 'melody_1_3',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 8,
      sound: 'melody_1_4',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 9,
      sound: 'melody_1_5',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody V',
    },
    {
      id: 10,
      sound: 'melody_1_6',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody VI',
    },
    {
      id: 11,
      sound: 'synth_1',
      color: PAD_COLORS.SYNTH_MAIN,
      group: 'synth',
      icon: 'synth',
      title: 'Synth I',
    },
    {
      id: 12,
      sound: 'synth_2',
      color: PAD_COLORS.SYNTH_SECONDARY,
      group: 'synth',
      icon: 'synth',
      title: 'Synth II',
    },
  ],
};

export default soundPack;
