require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable the next line.
flipper_config = ENV['NO_FLIPPER'] == "1" ? nil : {
  'Flipper' => '0.125.0',
  'Flipper-Folly' => '2.6.10',
  'Flipper-RSocket' => '1.4.3',
  'FlipperKit' => '0.125.0',
  'Flipper-DoubleConversion' => '3.2.0',
  'Flipper-Glog' => '0.5.0',
  'Flipper-PeerTalk' => '0.0.4',
  'FlipperKit/SKIOSNetworkPlugin' => '0.125.0',
  'FlipperKit/FlipperKitLayoutPlugin' => '0.125.0',
  'FlipperKit/FlipperKitUserDefaultsPlugin' => '0.125.0',
  'FlipperKit/FlipperKitReactPlugin' => '0.125.0'
}

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ShapeBeatsApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
