import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#E8F4F8',
  DRUMS_SECONDARY: '#D4E8F0',
  CLAP_MAIN: '#F0F8E8',
  CLAP_SECONDARY: '#E0F0D8',
  VOCAL_MAIN: '#F8E8F0',
  VOCAL_SECONDARY: '#F0D8E8',
  SFX_MAIN: '#FFF8E8',
  SFX_SECONDARY: '#FFF0D8',
};

const soundPack: SoundPack = {
  id: 'foreign',
  name: 'Foreign',
  genre: 'Hip Hop',
  bpm: '154',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    clap_1: require('./samples/clap_1.mp3'),
    clap_2: require('./samples/clap_2.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    drums_1: require('./samples/drums_1.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    drums_3: require('./samples/drums_3.mp3'),
    drums_4: require('./samples/drums_4.mp3'),
    vocal_1_1: require('./samples/vocal_1_1.mp3'),
    vocal_2_1: require('./samples/vocal_2_1.mp3'),
    vocal_2_2: require('./samples/vocal_2_2.mp3'),
    sfx_dubsteo: require('./samples/sfx_dubsteo.mp3'),
  },
  soundGroups: {
    drums: ['drums_1', 'drums_2', 'drums_3', 'drums_4'],
    clap: ['clap_1', 'clap_2'],
    vocal_1: ['vocal_1_1'],
    vocal_2: ['vocal_2_1', 'vocal_2_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'clap_1',
      color: PAD_COLORS.CLAP_MAIN,
      group: 'clap',
      icon: 'clap',
      title: 'Clap I',
    },
    {
      id: 3,
      sound: 'clap_2',
      color: PAD_COLORS.CLAP_SECONDARY,
      group: 'clap',
      icon: 'clap',
      title: 'Clap II',
    },
    {
      id: 4,
      sound: 'hi_hat',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 5,
      sound: 'drums_1',
      color: PAD_COLORS.DRUMS_MAIN,
      group: 'drums',
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 6,
      sound: 'drums_2',
      color: PAD_COLORS.DRUMS_MAIN,
      group: 'drums',
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 7,
      sound: 'drums_3',
      color: PAD_COLORS.DRUMS_SECONDARY,
      group: 'drums',
      icon: 'drums',
      title: 'Drums III',
    },
    {
      id: 8,
      sound: 'drums_4',
      color: PAD_COLORS.DRUMS_SECONDARY,
      group: 'drums',
      icon: 'drums',
      title: 'Drums IV',
    },
    {
      id: 9,
      sound: 'vocal_1_1',
      color: PAD_COLORS.VOCAL_MAIN,
      group: 'vocal_1',
      icon: 'vocal',
      title: 'Vocal I',
    },
    {
      id: 10,
      sound: 'vocal_2_1',
      color: PAD_COLORS.VOCAL_MAIN,
      group: 'vocal_2',
      icon: 'vocal',
      title: 'Vocal II',
    },
    {
      id: 11,
      sound: 'vocal_2_2',
      color: PAD_COLORS.VOCAL_SECONDARY,
      group: 'vocal_2',
      icon: 'vocal',
      title: 'Vocal III',
    },
    {
      id: 12,
      sound: 'sfx_dubsteo',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sfx',
      title: 'Dubstep',
    },
  ],
};

export default soundPack;
