import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#1A0A1A',
  DRUMS_SECONDARY: '#2A1A2A',
  BASS_MAIN: '#0F1A2A',
  BASS_SECONDARY: '#1A2A3A',
  HIHAT_MAIN: '#1A1A2A',
  HIHAT_SECONDARY: '#2A2A3A',
  MELODY_MAIN: '#2A1A3A',
  MELODY_SECONDARY: '#3A2A4A',
  SFX_MAIN: '#1A2A1A',
  SFX_SECONDARY: '#2A3A2A',
  CHANT_MAIN: '#3A1A1A',
};

const soundPack: SoundPack = {
  id: 'hype',
  name: 'Hype',
  genre: 'Trap',
  bpm: '140',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'dark',
  sounds: {
    kick: require('./samples/kick.mp3'),
    clap: require('./samples/clap.mp3'),
    hi_hat_roll_1: require('./samples/hi_hat_roll_1.mp3'),
    hi_hat_roll_2: require('./samples/hi_hat_roll_2.mp3'),
    '808_1': require('./samples/808_1.mp3'),
    '808_2': require('./samples/808_2.mp3'),
    '808_3': require('./samples/808_3.mp3'),
    synth_1: require('./samples/synth_1.mp3'),
    synth_2: require('./samples/synth_2.mp3'),
    sfx_glass: require('./samples/sfx_glass.mp3'),
    sfx_growl: require('./samples/sfx_growl.mp3'),
    chant_woo: require('./samples/chant_woo.mp3'),
  },
  soundGroups: {
    '808': ['808_1', '808_2', '808_3'],
    hi_hat_roll: ['hi_hat_roll_1', 'hi_hat_roll_2'],
    synth: ['synth_1', 'synth_2'],
    sfx: ['sfx_glass', 'sfx_growl'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 3,
      sound: 'hi_hat_roll_1',
      color: PAD_COLORS.HIHAT_MAIN,
      group: 'hi_hat_roll',
      icon: 'hi_hat',
      title: 'Hi Hat Roll I',
    },
    {
      id: 4,
      sound: 'hi_hat_roll_2',
      color: PAD_COLORS.HIHAT_SECONDARY,
      group: 'hi_hat_roll',
      icon: 'hi_hat',
      title: 'Hi Hat Roll II',
    },
    {
      id: 5,
      sound: '808_1',
      color: PAD_COLORS.BASS_MAIN,
      group: '808',
      icon: 'bass',
      title: '808 I',
    },
    {
      id: 6,
      sound: '808_2',
      color: PAD_COLORS.BASS_MAIN,
      group: '808',
      icon: 'bass',
      title: '808 II',
    },
    {
      id: 7,
      sound: '808_3',
      color: PAD_COLORS.BASS_SECONDARY,
      group: '808',
      icon: 'bass',
      title: '808 III',
    },
    {
      id: 8,
      sound: 'synth_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'synth',
      icon: 'synth',
      title: 'Synth I',
    },
    {
      id: 9,
      sound: 'synth_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'synth',
      icon: 'synth',
      title: 'Synth II',
    },
    {
      id: 10,
      sound: 'sfx_glass',
      color: PAD_COLORS.SFX_MAIN,
      group: 'sfx',
      icon: 'sfx',
      title: 'Glass',
    },
    {
      id: 11,
      sound: 'sfx_growl',
      color: PAD_COLORS.SFX_SECONDARY,
      group: 'sfx',
      icon: 'sfx',
      title: 'Growl',
    },
    {
      id: 12,
      sound: 'chant_woo',
      color: PAD_COLORS.CHANT_MAIN,
      icon: 'chant',
      title: 'Woo',
    },
  ],
};

export default soundPack;
