import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#F5F5F5',
  DRUMS_SECONDARY: '#E8E8E8',
  BASS_MAIN: '#F0F0F0',
  BASS_SECONDARY: '#E0E0E0',
  MELODY_MAIN: '#FFF5E6',
  MELODY_SECONDARY: '#FFE8CC',
  SFX_MAIN: '#E6F3FF',
  SFX_SECONDARY: '#D4E8FF',
  PERC_MAIN: '#F0F8FF',
};

const soundPack: SoundPack = {
  id: 'amex',
  name: 'Amex',
  genre: 'R&B',
  bpm: '154',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare: require('./samples/snare.mp3'),
    clap: require('./samples/clap.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    hit: require('./samples/hit.mp3'),
    '808_1': require('./samples/808_1.mp3'),
    '808_2': require('./samples/808_2.mp3'),
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    sfx_beep: require('./samples/sfx_beep.mp3'),
    sfx_growl: require('./samples/sfx_growl.mp3'),
  },
  soundGroups: {
    '808': ['808_1', '808_2'],
    melody: ['melody_1', 'melody_2', 'melody_3'],
    sfx: ['sfx_beep', 'sfx_growl'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 3,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 4,
      sound: 'hi_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 5,
      sound: 'hit',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hit',
      title: 'Hit',
    },
    {
      id: 6,
      sound: '808_1',
      color: PAD_COLORS.BASS_MAIN,
      group: '808',
      icon: 'bass',
      title: '808 I',
    },
    {
      id: 7,
      sound: '808_2',
      color: PAD_COLORS.BASS_SECONDARY,
      group: '808',
      icon: 'bass',
      title: '808 II',
    },
    {
      id: 8,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 9,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 10,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 11,
      sound: 'sfx_beep',
      color: PAD_COLORS.SFX_MAIN,
      group: 'sfx',
      icon: 'sfx',
      title: 'Beep',
    },
    {
      id: 12,
      sound: 'sfx_growl',
      color: PAD_COLORS.SFX_SECONDARY,
      group: 'sfx',
      icon: 'sfx',
      title: 'Growl',
    },
  ],
};

export default soundPack;
