import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#FFF8E1',
  DRUMS_SECONDARY: '#FFF3C4',
  SNARE_MAIN: '#FFE4B5',
  SNARE_SECONDARY: '#FFDAB9',
  MELODY_MAIN: '#F8F4E6',
  MELODY_SECONDARY: '#F5F0DC',
  PERCUSSION_MAIN: '#E6E6FA',
  CHANT_MAIN: '#FFE1E1',
};

const soundPack: SoundPack = {
  id: 'myWay',
  name: 'My Way',
  genre: 'R&B',
  bpm: '120',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare_1: require('./samples/snare_1.mp3'),
    snare_2: require('./samples/snare_2.mp3'),
    clap_1: require('./samples/clap_1.mp3'),
    clap_2: require('./samples/clap_2.mp3'),
    percussion: require('./samples/percussion.mp3'),
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    melody_4: require('./samples/melody_4.mp3'),
    melody_5: require('./samples/melody_5.mp3'),
    chant: require('./samples/chant.mp3'),
  },
  soundGroups: {
    snare: ['snare_1', 'snare_2'],
    clap: ['clap_1', 'clap_2'],
    melody: ['melody_1', 'melody_2', 'melody_3', 'melody_4', 'melody_5'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare_1',
      color: PAD_COLORS.SNARE_MAIN,
      group: 'snare',
      icon: 'snare',
      title: 'Snare I',
    },
    {
      id: 3,
      sound: 'snare_2',
      color: PAD_COLORS.SNARE_SECONDARY,
      group: 'snare',
      icon: 'snare',
      title: 'Snare II',
    },
    {
      id: 4,
      sound: 'clap_1',
      color: PAD_COLORS.DRUMS_MAIN,
      group: 'clap',
      icon: 'clap',
      title: 'Clap I',
    },
    {
      id: 5,
      sound: 'clap_2',
      color: PAD_COLORS.DRUMS_SECONDARY,
      group: 'clap',
      icon: 'clap',
      title: 'Clap II',
    },
    {
      id: 6,
      sound: 'percussion',
      color: PAD_COLORS.PERCUSSION_MAIN,
      icon: 'percussion',
      title: 'Percussion',
    },
    {
      id: 7,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 8,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 9,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 10,
      sound: 'melody_4',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 11,
      sound: 'melody_5',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody V',
    },
    {
      id: 12,
      sound: 'chant',
      color: PAD_COLORS.CHANT_MAIN,
      icon: 'chant',
      title: 'Chant',
    },
  ],
};

export default soundPack;
