import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#FFF8DC',
  DRUMS_SECONDARY: '#FFEBCD',
  BASS_MAIN: '#FFE4B5',
  MELODY_MAIN: '#FFB6C1',
  MELODY_SECONDARY: '#FFCCCB',
};

const soundPack: SoundPack = {
  id: 'locoContigo',
  name: 'Loco Contigo',
  genre: 'R&B',
  bpm: '113',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    drums: require('./samples/drums.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    clap: require('./samples/clap.mp3'),
    snare_roll: require('./samples/snare_roll.mp3'),
    percussion: require('./samples/percussion.mp3'),
    bass_808: require('./samples/808.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_2_1: require('./samples/melody_2_1.mp3'),
    melody_2_2: require('./samples/melody_2_2.mp3'),
    melody_3_1: require('./samples/melody_3_1.mp3'),
    melody_3_2: require('./samples/melody_3_2.mp3'),
  },
  soundGroups: {
    melody_1: ['melody_1_1', 'melody_1_2'],
    melody_2: ['melody_2_1', 'melody_2_2'],
    melody_3: ['melody_3_1', 'melody_3_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'drums',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums',
    },
    {
      id: 2,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 3,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 4,
      sound: 'snare_roll',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'snare',
      title: 'Snare Roll',
    },
    {
      id: 5,
      sound: 'percussion',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'percussion',
      title: 'Percussion',
    },
    {
      id: 6,
      sound: 'bass_808',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'bass',
      title: '808 Bass',
    },
    {
      id: 7,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'trumpet',
      title: 'Trumpet I',
    },
    {
      id: 8,
      sound: 'melody_2_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'trumpet',
      title: 'Trumpet II',
    },
    {
      id: 9,
      sound: 'melody_3_1',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 10,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'trumpet',
      title: 'Trumpet III',
    },
    {
      id: 11,
      sound: 'melody_2_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'trumpet',
      title: 'Trumpet IV',
    },
    {
      id: 12,
      sound: 'melody_3_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'melody',
      title: 'Melody II',
    },
  ],
};

export default soundPack;
