import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#E0F8F8',
  DRUMS_SECONDARY: '#D0E8E8',
  BASS_MAIN: '#C0E8F0',
  BASS_SECONDARY: '#B0D8E0',
  MELODY_MAIN: '#F0F8F8',
  MELODY_SECONDARY: '#E8F0F0',
  SFX_MAIN: '#F8F8F8',
  SFX_SECONDARY: '#F0F0F0',
  PERC_MAIN: '#D8F0F8',
};

const soundPack: SoundPack = {
  id: 'genesis',
  name: 'Genesis',
  genre: 'Trap',
  bpm: '130',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare: require('./samples/snare.mp3'),
    snap: require('./samples/snap.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    hi_hat_roll: require('./samples/hi_hat_roll.mp3'),
    hit: require('./samples/hit.mp3'),
    '808_1': require('./samples/808_1.mp3'),
    '808_2': require('./samples/808_2.mp3'),
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    sfx_alien: require('./samples/sfx_alien.mp3'),
  },
  soundGroups: {
    '808': ['808_1', '808_2'],
    melody: ['melody_1', 'melody_2', 'melody_3'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 3,
      sound: 'snap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snap',
    },
    {
      id: 4,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 5,
      sound: 'hi_hat_roll',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hi_hat',
      title: 'Hi Hat Roll',
    },
    {
      id: 6,
      sound: 'hit',
      color: PAD_COLORS.PERC_MAIN,
      icon: 'hit',
      title: 'Hit',
    },
    {
      id: 7,
      sound: '808_1',
      color: PAD_COLORS.BASS_MAIN,
      group: '808',
      icon: 'bass',
      title: '808 I',
    },
    {
      id: 8,
      sound: '808_2',
      color: PAD_COLORS.BASS_SECONDARY,
      group: '808',
      icon: 'bass',
      title: '808 II',
    },
    {
      id: 9,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 10,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 11,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 12,
      sound: 'sfx_alien',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sfx',
      title: 'Alien',
    },
  ],
};

export default soundPack;
