import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#2d1b1b',
  DRUMS_SECONDARY: '#3d2b2b',
  MELODY_MAIN: '#1b1b2d',
  MELODY_SECONDARY: '#2b2b3d',
  SFX_MAIN: '#2d1b2d',
  SFX_SECONDARY: '#3d2b3d',
};

const soundPack: SoundPack = {
  id: 'katana',
  name: 'Katana',
  genre: 'Trap',
  bpm: '140',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    drums_1: require('./samples/drums_1.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    drums_3: require('./samples/drums_3.mp3'),
    snare: require('./samples/snare.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    synth: require('./samples/synth.mp3'),
    sfx_sword_1: require('./samples/sfx_sword_1.mp3'),
    sfx_sword_2: require('./samples/sfx_sword_2.mp3'),
    sfx_reverse: require('./samples/sfx_reverse.mp3'),
  },
  soundGroups: {
    drums: ['drums_1', 'drums_2', 'drums_3'],
    melody_1: ['melody_1_1', 'melody_1_2'],
    melody_2and3: ['melody_2', 'melody_3'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'drums_1',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 2,
      sound: 'drums_2',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 3,
      sound: 'drums_3',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums III',
    },
    {
      id: 4,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 5,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 6,
      sound: 'synth',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'synth',
      title: 'Synth',
    },
    {
      id: 7,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 8,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 9,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 10,
      sound: 'sfx_sword_1',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sword',
      title: 'Sword I',
    },
    {
      id: 11,
      sound: 'sfx_sword_2',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sword',
      title: 'Sword II',
    },
    {
      id: 12,
      sound: 'sfx_reverse',
      color: PAD_COLORS.SFX_SECONDARY,
      icon: 'reverse',
      title: 'Reverse',
    },
  ],
};

export default soundPack;
