import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#C0C0C0',
  DRUMS_SECONDARY: '#F0F0F0',
  BASS_MAIN: '#D0D0D0',
  BASS_SECONDARY: '#E8E8E8',
  MELODY_MAIN: '#C8E6C8',
  MELODY_SECONDARY: '#E8F5E8',
  SFX_MAIN: '#B0E0B0',
  SFX_SECONDARY: '#D8F0D8',
};

const soundPack: SoundPack = {
  id: 'yamaha',
  name: 'Yamaha',
  genre: 'Hip Hop',
  bpm: '140',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    choir_1: require('./samples/choir_1.mp3'),
    choir_2: require('./samples/choir_2.mp3'),
    choir_3: require('./samples/choir_3.mp3'),
    kick: require('./samples/kick.mp3'),
    snare_1: require('./samples/snare_1.mp3'),
    snare_2: require('./samples/snare_2.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    snap: require('./samples/snap.mp3'),
    drums_1: require('./samples/drums_1.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    sfx_motorbike: require('./samples/sfx_motorbike.mp3'),
  },
  soundGroups: {
    melodies: ['choir_1', 'choir_2', 'choir_3'],
    drums: ['drums_1', 'drums_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare_1',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare I',
    },
    {
      id: 3,
      sound: 'snare_2',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare II',
    },
    {
      id: 4,
      sound: 'hi_hat',
      color: PAD_COLORS.BASS_SECONDARY,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 5,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 6,
      sound: 'snap',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'snap',
      title: 'Snap',
    },
    {
      id: 7,
      sound: 'drums_1',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 8,
      sound: 'drums_2',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 9,
      sound: 'choir_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'choir_male',
      title: 'Choir I',
    },
    {
      id: 10,
      sound: 'choir_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'choir_male',
      title: 'Choir II',
    },
    {
      id: 11,
      sound: 'choir_3',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'choir_female',
      title: 'Choir III',
    },
    {
      id: 12,
      sound: 'sfx_motorbike',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'sfx',
      title: 'Motorbike',
    },
  ],
};

export default soundPack;
