import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#CD5C5C',
  DRUMS_SECONDARY: '#E6B3B3',
  BASS_MAIN: '#A9A9A9',
  BASS_SECONDARY: '#C0C0C0',
  MELODY_MAIN: '#9370DB',
  MELODY_SECONDARY: '#B8A9D9',
  SFX_MAIN: '#6495ED',
  SFX_SECONDARY: '#A7C7E7',
};

const soundPack: SoundPack = {
  id: 'vendetta',
  name: 'Vendetta',
  genre: 'Trap',
  bpm: '100',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    melody_4: require('./samples/melody_4.mp3'),
    synth_1: require('./samples/synth_1.mp3'),
    synth_2: require('./samples/synth_2.mp3'),
    chant_demon: require('./samples/chant_demon.mp3'),
    chant_die: require('./samples/chant_die.mp3'),
    chant_sorry: require('./samples/chant_sorry.mp3'),
    snare: require('./samples/snare.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    clap_1: require('./samples/clap_1.mp3'),
    clap_2: require('./samples/clap_2.mp3'),
    hit_1: require('./samples/hit_1.mp3'),
    hit_2: require('./samples/hit_2.mp3'),
    drums_1: require('./samples/drums_1.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    percussion: require('./samples/percussion.mp3'),
    bass_808: require('./samples/808.mp3'),
    sfx_chains: require('./samples/sfx_chains.mp3'),
    sfx_distortion: require('./samples/sfx_distortion.mp3'),
    sfx_dubstep_drop: require('./samples/sfx_dubstep_drop.mp3'),
    sfx_dubstep_filler: require('./samples/sfx_dubstep_filler.mp3'),
    sfx_glass: require('./samples/sfx_glass.mp3'),
  },
  soundGroups: {
    melodies: ['melody_1', 'melody_2', 'melody_3', 'melody_4'],
    sfx: [
      'sfx_chains',
      'sfx_distortion',
      'sfx_dubstep_drop',
      'sfx_dubstep_filler',
      'sfx_glass',
    ],
    chants: ['chant_demon', 'chant_die', 'chant_sorry'],
    drums: ['drums_1', 'drums_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 2,
      sound: 'hi_hat',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 3,
      sound: 'clap_1',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap I',
    },
    {
      id: 4,
      sound: 'clap_2',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'clap',
      title: 'Clap II',
    },
    {
      id: 5,
      sound: 'hit_1',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hit',
      title: 'Hit I',
    },
    {
      id: 6,
      sound: 'hit_2',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hit',
      title: 'Hit II',
    },
    {
      id: 7,
      sound: 'drums_1',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 8,
      sound: 'drums_2',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 9,
      sound: 'percussion',
      color: PAD_COLORS.BASS_SECONDARY,
      icon: 'percussion',
      title: 'Percussion',
    },
    {
      id: 10,
      sound: 'bass_808',
      color: PAD_COLORS.BASS_SECONDARY,
      icon: 'bass',
      title: '808 Bass',
    },
    {
      id: 11,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 12,
      sound: 'synth_1',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'synth',
      title: 'Synth I',
    },
    {
      id: 13,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 14,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 15,
      sound: 'melody_4',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 16,
      sound: 'synth_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'synth',
      title: 'Synth II',
    },
    {
      id: 17,
      sound: 'chant_demon',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'chant',
      title: 'Demon Chant',
    },
    {
      id: 18,
      sound: 'chant_die',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'chant',
      title: 'Die Chant',
    },
    {
      id: 19,
      sound: 'chant_sorry',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'chant',
      title: 'Sorry Chant',
    },
    {
      id: 20,
      sound: 'sfx_chains',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sfx',
      title: 'Chains',
    },
    {
      id: 21,
      sound: 'sfx_distortion',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sfx',
      title: 'Distortion',
    },
    {
      id: 22,
      sound: 'sfx_dubstep_drop',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sfx',
      title: 'Dubstep Drop',
    },
    {
      id: 23,
      sound: 'sfx_dubstep_filler',
      color: PAD_COLORS.SFX_SECONDARY,
      icon: 'sfx',
      title: 'Dubstep Filler',
    },
    {
      id: 24,
      sound: 'sfx_glass',
      color: PAD_COLORS.SFX_SECONDARY,
      icon: 'sfx',
      title: 'Glass',
    },
  ],
};

export default soundPack;
