import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#E0E8F0',
  DRUMS_SECONDARY: '#D0D8E0',
  KICK_MAIN: '#F0E8E0',
  KICK_SECONDARY: '#E8D8D0',
  MELODY_MAIN: '#F0F0E8',
  MELODY_SECONDARY: '#E8E8E0',
  PERCUSSION_MAIN: '#E8F0E8',
  PERCUSSION_SECONDARY: '#E0E8E0',
  VOCAL_MAIN: '#F8E8F0',
  VOCAL_SECONDARY: '#F0E0E8',
};

const soundPack: SoundPack = {
  id: 'digital',
  name: 'Digital',
  genre: 'Trap',
  bpm: '140',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    snare: require('./samples/snare.mp3'),
    kick_1: require('./samples/kick_1.mp3'),
    kick_2: require('./samples/kick_2.mp3'),
    kicks_roll: require('./samples/kicks_roll.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_2_1: require('./samples/melody_2_1.mp3'),
    melody_2_2: require('./samples/melody_2_2.mp3'),
    percussion_1: require('./samples/percussion_1.mp3'),
    percussion_2: require('./samples/percussion_2.mp3'),
    vocal_1: require('./samples/vocal_1.mp3'),
    vocal_2: require('./samples/vocal_2.mp3'),
  },
  soundGroups: {
    kick: ['kick_1', 'kick_2'],
    melody_1: ['melody_1_1', 'melody_1_2'],
    melody_2: ['melody_2_1', 'melody_2_2'],
    percussion: ['percussion_1', 'percussion_2'],
    vocal: ['vocal_1', 'vocal_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 2,
      sound: 'kick_1',
      color: PAD_COLORS.KICK_MAIN,
      group: 'kick',
      icon: 'kick',
      title: 'Kick I',
    },
    {
      id: 3,
      sound: 'kick_2',
      color: PAD_COLORS.KICK_SECONDARY,
      group: 'kick',
      icon: 'kick',
      title: 'Kick II',
    },
    {
      id: 4,
      sound: 'kicks_roll',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'kick',
      title: 'Kicks Roll',
    },
    {
      id: 5,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 6,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 7,
      sound: 'melody_2_1',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 8,
      sound: 'melody_2_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 9,
      sound: 'percussion_1',
      color: PAD_COLORS.PERCUSSION_MAIN,
      group: 'percussion',
      icon: 'percussion',
      title: 'Percussion I',
    },
    {
      id: 10,
      sound: 'percussion_2',
      color: PAD_COLORS.PERCUSSION_SECONDARY,
      group: 'percussion',
      icon: 'percussion',
      title: 'Percussion II',
    },
    {
      id: 11,
      sound: 'vocal_1',
      color: PAD_COLORS.VOCAL_MAIN,
      group: 'vocal',
      icon: 'vocal',
      title: 'Vocal I',
    },
    {
      id: 12,
      sound: 'vocal_2',
      color: PAD_COLORS.VOCAL_SECONDARY,
      group: 'vocal',
      icon: 'vocal',
      title: 'Vocal II',
    },
  ],
};

export default soundPack;
