import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#D3D3D3',
  DRUMS_SECONDARY: '#E9E9E9',
  BASS_MAIN: '#A9A9A9',
  BASS_SECONDARY: '#C0C0C0',
  MELODY_MAIN: '#C0C0C0',
  MELODY_SECONDARY: '#D3D3D3',
  SFX_MAIN: '#E9E9E9',
  SFX_SECONDARY: '#F5F5F5',
};

const soundPack: SoundPack = {
  id: 'maskOff',
  name: 'Mask Off',
  genre: 'Trap',
  bpm: '134',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    synth: require('./samples/synth.mp3'),
    chant_1: require('./samples/chant_1.mp3'),
    chant_2: require('./samples/chant_2.mp3'),
    drums_1: require('./samples/drums_1.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    drums_3: require('./samples/drums_3.mp3'),
    hit_1: require('./samples/hit_1.mp3'),
    hit_2: require('./samples/hit_2.mp3'),
    snare: require('./samples/snare.mp3'),
    sfx_dubstep_filler: require('./samples/sfx_dubstep_filler.mp3'),
  },
  soundGroups: {
    drums: ['drums_1', 'drums_2', 'drums_3'],
    melodies: ['melody_1', 'melody_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'drums_1',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 2,
      sound: 'drums_2',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 3,
      sound: 'drums_3',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums III',
    },
    {
      id: 4,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 5,
      sound: 'hit_1',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hit',
      title: 'Hit I',
    },
    {
      id: 6,
      sound: 'hit_2',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hit',
      title: 'Hit II',
    },
    {
      id: 7,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 8,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 9,
      sound: 'synth',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'synth',
      title: 'Synth',
    },
    {
      id: 10,
      sound: 'chant_1',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'chant',
      title: 'Chant I',
    },
    {
      id: 11,
      sound: 'chant_2',
      color: PAD_COLORS.BASS_SECONDARY,
      icon: 'chant',
      title: 'Chant II',
    },
    {
      id: 12,
      sound: 'sfx_dubstep_filler',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'sfx',
      title: 'Dubstep Filler',
    },
  ],
};

export default soundPack;
