import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#FFEAA7',
  DRUMS_SECONDARY: '#FFF2CC',
  BASS_MAIN: '#FFE4B5',
  BASS_SECONDARY: '#FFF8DC',
  MELODY_MAIN: '#FFD4AA',
  MELODY_SECONDARY: '#FFE6CC',
  SFX_MAIN: '#FFCBA4',
  SFX_SECONDARY: '#FFDCC0',
};

const soundPack: SoundPack = {
  id: 'shiva',
  name: 'Shiva',
  genre: 'Indian Trap',
  bpm: '95',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    flute: require('./samples/flute.mp3'),
    chant_hey: require('./samples/chant_hey.mp3'),
    drums_1_1: require('./samples/drums_1_1.mp3'),
    drums_1_2: require('./samples/drums_1_2.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    clap: require('./samples/clap.mp3'),
    hit: require('./samples/hit.mp3'),
    shaker: require('./samples/shaker.mp3'),
    percussion_1: require('./samples/percussion_1.mp3'),
    percussion_2: require('./samples/percussion_2.mp3'),
  },
  soundGroups: {
    melodies: ['melody_1', 'melody_2'],
    drums: ['drums_1_1', 'drums_1_2', 'drums_2'],
    percussion: ['percussion_1', 'percussion_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'drums_1_1',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 2,
      sound: 'drums_1_2',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 3,
      sound: 'drums_2',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'drums',
      title: 'Drums III',
    },
    {
      id: 4,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 5,
      sound: 'hit',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'hit',
      title: 'Hit',
    },
    {
      id: 6,
      sound: 'shaker',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'shaker',
      title: 'Shaker',
    },
    {
      id: 7,
      sound: 'percussion_1',
      color: PAD_COLORS.BASS_SECONDARY,
      icon: 'percussion',
      title: 'Percussion I',
    },
    {
      id: 8,
      sound: 'percussion_2',
      color: PAD_COLORS.BASS_SECONDARY,
      icon: 'percussion',
      title: 'Percussion II',
    },
    {
      id: 9,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 10,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 11,
      sound: 'flute',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'flute',
      title: 'Flute',
    },
    {
      id: 12,
      sound: 'chant_hey',
      color: PAD_COLORS.SFX_MAIN,
      icon: 'chant',
      title: 'Hey Chant',
    },
  ],
};

export default soundPack;
