import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#E8D5A3',
  DRUMS_SECONDARY: '#F0E6C8',
  BASS_MAIN: '#F0F0F0',
  HIHAT_MAIN: '#E8E8E8',
  MELODY_MAIN: '#F5E6D3',
  MELODY_SECONDARY: '#F7E7CE',
  SFX_MAIN: '#F5F5F5',
  SFX_SECONDARY: '#FFF8DC',
};

const soundPack: SoundPack = {
  id: 'ferragamo',
  name: 'Ferragamo',
  genre: 'Drum & Bass',
  bpm: '152',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    kick: require('./samples/kick.mp3'),
    snare: require('./samples/snare.mp3'),
    clap: require('./samples/clap.mp3'),
    open_hat: require('./samples/open_hat.mp3'),
    crash: require('./samples/crash.mp3'),
    hi_hat_roll: require('./samples/hi_hat_roll.mp3'),
    '808': require('./samples/808.mp3'),
    melody_1_1: require('./samples/melody_1_1.mp3'),
    melody_1_2: require('./samples/melody_1_2.mp3'),
    melody_1_3: require('./samples/melody_1_3.mp3'),
    melody_2_1: require('./samples/melody_2_1.mp3'),
    melody_2_2: require('./samples/melody_2_2.mp3'),
  },
  soundGroups: {
    melody_1: ['melody_1_1', 'melody_1_2', 'melody_1_3'],
    melody_2: ['melody_2_1', 'melody_2_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'snare',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'snare',
      title: 'Snare',
    },
    {
      id: 3,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 4,
      sound: 'open_hat',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Open Hat',
    },
    {
      id: 5,
      sound: 'crash',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'percussion',
      title: 'Crash',
    },
    {
      id: 6,
      sound: 'hi_hat_roll',
      color: PAD_COLORS.HIHAT_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat Roll',
    },
    {
      id: 7,
      sound: '808',
      color: PAD_COLORS.BASS_MAIN,
      icon: 'bass',
      title: '808',
    },
    {
      id: 8,
      sound: 'melody_1_1',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 9,
      sound: 'melody_1_2',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 10,
      sound: 'melody_1_3',
      color: PAD_COLORS.MELODY_MAIN,
      group: 'melody_1',
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 11,
      sound: 'melody_2_1',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody IV',
    },
    {
      id: 12,
      sound: 'melody_2_2',
      color: PAD_COLORS.MELODY_SECONDARY,
      group: 'melody_2',
      icon: 'melody',
      title: 'Melody V',
    },
  ],
};

export default soundPack;
