import {PadColors, SoundPack} from '../../../../types/soundPacks';

const PAD_COLORS: PadColors = {
  DRUMS_MAIN: '#D8BFD8',
  DRUMS_SECONDARY: '#E6D3E6',
  MELODY_MAIN: '#FFB6C1',
  MELODY_SECONDARY: '#FFC0CB',
  SFX_MAIN: '#E6E6FA',
  SFX_SECONDARY: '#F0F0FF',
  PERCUSSION_MAIN: '#FFB6C1',
  PERCUSSION_SECONDARY: '#FFC0CB',
};

const soundPack: SoundPack = {
  id: 'zenith',
  name: 'Zenith',
  genre: 'R&B',
  bpm: '120',
  cover: require('./cover.jpg'),
  demo: require('./demo.mp3'),
  theme: 'light',
  sounds: {
    melody_1: require('./samples/melody_1.mp3'),
    melody_2: require('./samples/melody_2.mp3'),
    melody_3: require('./samples/melody_3.mp3'),
    kick: require('./samples/kick.mp3'),
    clap: require('./samples/clap.mp3'),
    hi_hat: require('./samples/hi_hat.mp3'),
    crash: require('./samples/crash.mp3'),
    drums_1: require('./samples/drums_1.mp3'),
    drums_2: require('./samples/drums_2.mp3'),
    percussion_1: require('./samples/percussion_1.mp3'),
    percussion_2: require('./samples/percussion_2.mp3'),
    vocal: require('./samples/vocal.mp3'),
  },
  soundGroups: {
    melodies: ['melody_1', 'melody_2', 'melody_3'],
    drums: ['drums_1', 'drums_2'],
  },
  padConfig: [
    {
      id: 1,
      sound: 'kick',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'kick',
      title: 'Kick',
    },
    {
      id: 2,
      sound: 'clap',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'clap',
      title: 'Clap',
    },
    {
      id: 3,
      sound: 'hi_hat',
      color: PAD_COLORS.DRUMS_MAIN,
      icon: 'hi_hat',
      title: 'Hi Hat',
    },
    {
      id: 4,
      sound: 'crash',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'open_hat',
      title: 'Crash',
    },
    {
      id: 5,
      sound: 'drums_1',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'drums',
      title: 'Drums I',
    },
    {
      id: 6,
      sound: 'drums_2',
      color: PAD_COLORS.DRUMS_SECONDARY,
      icon: 'drums',
      title: 'Drums II',
    },
    {
      id: 7,
      sound: 'percussion_1',
      color: PAD_COLORS.PERCUSSION_MAIN,
      icon: 'percussion',
      title: 'Percussion I',
    },
    {
      id: 8,
      sound: 'percussion_2',
      color: PAD_COLORS.PERCUSSION_SECONDARY,
      icon: 'percussion',
      title: 'Percussion II',
    },
    {
      id: 9,
      sound: 'melody_1',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody I',
    },
    {
      id: 10,
      sound: 'melody_2',
      color: PAD_COLORS.MELODY_MAIN,
      icon: 'melody',
      title: 'Melody II',
    },
    {
      id: 11,
      sound: 'melody_3',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'melody',
      title: 'Melody III',
    },
    {
      id: 12,
      sound: 'vocal',
      color: PAD_COLORS.MELODY_SECONDARY,
      icon: 'vocal',
      title: 'Vocal',
    },
  ],
};

export default soundPack;
